
  CREATE TABLE "LOG_PROCEDURE" 
   (	"PROCEDURE_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"ACTION_DATE" TIMESTAMP (6), 
	"ACTION_RESULT" VARCHAR2(64), 
	"ACTION_STEP" VARCHAR2(64), 
	"PROCEDURE_ID" NUMBER, 
	"USER_NAME" VARCHAR2(64)
   ) ;

   COMMENT ON COLUMN "LOG_PROCEDURE"."PROCEDURE_NAME" IS 'Название процедуры';
   COMMENT ON COLUMN "LOG_PROCEDURE"."ACTION_DATE" IS 'Дата запуска';
   COMMENT ON COLUMN "LOG_PROCEDURE"."ACTION_RESULT" IS 'Описание шага';
   COMMENT ON COLUMN "LOG_PROCEDURE"."ACTION_STEP" IS 'Шаг';
   COMMENT ON COLUMN "LOG_PROCEDURE"."PROCEDURE_ID" IS 'ID процедуры';
   COMMENT ON COLUMN "LOG_PROCEDURE"."USER_NAME" IS 'Имя пользователя';