create or replace PACKAGE TEST_LOG IS 
 
PROCEDURE RUN_LOG_PROCEDURE( 
    PROCEDURE_NAME VARCHAR2, 
    ACTION_RESULT VARCHAR2, 
    ACTION_STEP VARCHAR2, 
    PROCEDURE_ID NUMBER 
); 
 
PROCEDURE TEST_INSERT_x_UPDATE(PROCEDURE_ID NUMBER); 
 
PROCEDURE TEST_DELETE(PROCEDURE_ID NUMBER); 
 
END TEST_LOG;
/